services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  solr:
    image: solr:9
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: solr-precreate documents

volumes:
  mongo_data:
  solr_data:
